#!/usr/bin/env python3
"""
Merge upstream coc_combined COC entries into grouped keyframe categories.

The grouped category JSON uses:
  - chunk_id
  - clip_id
  - keyframe_index: actual video frame index

The upstream coc_combined file is generated by a separate COC pipeline:
  labels/coc_combined/coc_combined.{chunk_id}/{clip_id}.coc_combined.json

Each upstream keyframe contains a 31-frame coc_list window around that COC
pipeline keyframe. The meta_actions keyframes used by typical_scenario_key_frame
do not have to be identical to the COC pipeline keyframes.

Matching strategy:
  1. Open the coc_combined file by chunk_id + clip_id.
  2. Search top-level keyframes in file order.
  3. Pick the first upstream keyframe whose coc_list contains our frame index.
  4. If none contains it, set coc to null.

The merged output stores the selected COC text as a plain string. Missing or
empty COC values are written as "".
"""

import argparse
import json
import os
from collections import Counter
from copy import deepcopy
from pathlib import Path
from typing import Any


def default_data_dir() -> Path:
    env_data_dir = os.getenv("ALPAMAYO_DATA_DIR")
    if env_data_dir:
        return Path(env_data_dir)

    repo_data_dir = (
        Path(__file__).resolve().parents[2]
        / "data"
        / "PhysicalAI-Autonomous-Vehicles"
    )
    if repo_data_dir.exists():
        return repo_data_dir

    return Path("/home/xingao/code/Alpamayo1.5/data/PhysicalAI-Autonomous-Vehicles")


def category_sort_value(category: str) -> tuple[int, int | str]:
    try:
        return (0, int(category))
    except ValueError:
        return (1, category)


def group_sort_key(group_key: str) -> tuple[str, tuple[int, int | str]]:
    prompt_name, _, category = group_key.rpartition("_category_")
    return prompt_name, category_sort_value(category)


def load_category_groups(path: Path) -> dict[str, list[dict[str, Any]]]:
    with open(path, "r", encoding="utf-8") as f:
        groups = json.load(f)
    if not isinstance(groups, dict):
        raise ValueError(f"Expected category JSON object, got {type(groups).__name__}")
    return {
        key: groups[key]
        for key in sorted(groups.keys(), key=group_sort_key)
    }


def coc_combined_file(coc_combined_dir: Path, chunk_id: str, clip_id: str) -> Path:
    return (
        coc_combined_dir
        / f"coc_combined.{chunk_id}"
        / f"{clip_id}.coc_combined.json"
    )


def load_coc_combined_file(
    path: Path,
    cache: dict[Path, dict[str, Any] | None],
) -> dict[str, Any] | None:
    if path in cache:
        return cache[path]

    if not path.exists():
        cache[path] = None
        return None

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    cache[path] = data
    return data


def parse_int(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def extract_coc_text(raw_value: Any) -> str:
    """Extract the text from raw coc_list values such as [[text]]."""
    value = raw_value
    while isinstance(value, list) and value:
        value = value[0]
    if value is None or value == []:
        return ""
    return str(value)


def find_first_coc_match(
    coc_file_data: dict[str, Any],
    target_frame_key: str,
) -> tuple[str, int]:
    first_match = None
    candidate_count = 0

    for source_keyframe_key, source_entry in coc_file_data.items():
        if source_keyframe_key == "clip_id" or not isinstance(source_entry, dict):
            continue

        coc_list = source_entry.get("coc_list", {})
        if not isinstance(coc_list, dict) or target_frame_key not in coc_list:
            continue

        candidate_count += 1
        if first_match is not None:
            continue

        raw_coc = coc_list.get(target_frame_key)
        first_match = extract_coc_text(raw_coc)

    return first_match or "", candidate_count


def merge_groups(
    groups: dict[str, list[dict[str, Any]]],
    coc_combined_dir: Path,
) -> tuple[dict[str, list[dict[str, Any]]], Counter]:
    merged_groups: dict[str, list[dict[str, Any]]] = {}
    stats: Counter = Counter()
    file_cache: dict[Path, dict[str, Any] | None] = {}

    for group_key, items in groups.items():
        merged_items = []
        for item in items:
            stats["category_records"] += 1
            merged_item = deepcopy(item)

            clip_id = str(item.get("clip_id", ""))
            chunk_id = str(item.get("chunk_id", ""))
            keyframe_key = str(item.get("keyframe_index", ""))
            path = coc_combined_file(coc_combined_dir, chunk_id, clip_id)

            coc_file_data = load_coc_combined_file(path, file_cache)
            if coc_file_data is None:
                merged_item["coc"] = ""
                stats["missing_coc_combined_file"] += 1
                merged_items.append(merged_item)
                continue

            coc_text, candidate_count = find_first_coc_match(coc_file_data, keyframe_key)
            if candidate_count == 0:
                merged_item["coc"] = ""
                stats["missing_frame_in_coc_list"] += 1
                merged_items.append(merged_item)
                continue

            merged_item["coc"] = coc_text
            stats["matched_coc_frame"] += 1
            if candidate_count > 1:
                stats["multi_candidate_coc_frame"] += 1
            if not coc_text:
                stats["empty_coc_text"] += 1
            merged_items.append(merged_item)

        merged_groups[group_key] = merged_items

    stats["loaded_coc_combined_files"] = sum(1 for value in file_cache.values() if value is not None)
    stats["missing_coc_combined_files"] = sum(1 for value in file_cache.values() if value is None)
    return merged_groups, stats


def parse_args() -> argparse.Namespace:
    data_dir = default_data_dir()
    default_category_json = (
        data_dir
        / "labels"
        / "typical_scenario_key_frame"
        / "typical_scenario_key_frame_category.json"
    )
    default_coc_combined_dir = data_dir / "labels" / "coc_combined"
    default_output = (
        data_dir
        / "labels"
        / "typical_scenario_key_frame"
        / "typical_scenario_key_frame_category_coc.json"
    )

    parser = argparse.ArgumentParser(
        description="Merge coc_combined frame COC entries into grouped keyframe category JSON."
    )
    parser.add_argument("--category-json", type=Path, default=default_category_json,
                        help="Input typical_scenario_key_frame_category.json")
    parser.add_argument("--coc-combined-dir", type=Path, default=default_coc_combined_dir,
                        help="Input labels/coc_combined directory")
    parser.add_argument("--output", type=Path, default=default_output,
                        help="Output merged JSON path")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.category_json.exists():
        raise FileNotFoundError(f"Category JSON not found: {args.category_json}")
    if not args.coc_combined_dir.exists():
        raise FileNotFoundError(f"coc_combined directory not found: {args.coc_combined_dir}")

    groups = load_category_groups(args.category_json)
    merged_groups, stats = merge_groups(groups, args.coc_combined_dir)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(merged_groups, f, ensure_ascii=False, indent=2)

    print(f"Loaded category groups: {args.category_json} ({len(groups)} groups)")
    print(f"Loaded coc_combined:    {args.coc_combined_dir}")
    print(f"Saved merged JSON:     {args.output}")
    print(
        "Merge stats: "
        f"{stats['category_records']} records, "
        f"{stats['matched_coc_frame']} matched, "
        f"{stats['missing_frame_in_coc_list']} missing frame, "
        f"{stats['multi_candidate_coc_frame']} multi-candidate, "
        f"{stats['empty_coc_text']} empty text, "
        f"{stats['missing_coc_combined_file']} missing file"
    )
    print(
        "File cache: "
        f"{stats['loaded_coc_combined_files']} loaded, "
        f"{stats['missing_coc_combined_files']} missing"
    )


if __name__ == "__main__":
    main()
